# Generated by Django 5.0.4 on 2024-05-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscribed',
            new_name='is_subscription',
        ),
    ]
