# Generated by Django 5.0.4 on 2024-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_subscribed_user_is_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
    ]
