# Generated by Django 5.0.4 on 2024-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
    ]
